#!/usr/bin/env python3
"""Generate static Markdown API docs from package docstrings."""

from __future__ import annotations

import argparse
import importlib
import inspect
import warnings
from pathlib import Path
from types import ModuleType
from typing import Any

DEFAULT_MODULE_MAP: dict[str, str] = {
    "modeling": "deberta.modeling",
    "data": "deberta.data",
    "training": "deberta.training",
}

warnings.filterwarnings(
    "ignore",
    message="CUDA initialization: Unexpected error from cudaGetDeviceCount.*",
    category=UserWarning,
)


def _format_docstring(value: Any) -> str:
    doc = inspect.getdoc(value)
    if not doc:
        return "No docstring available."
    return doc.strip()


def _format_signature(value: Any, *, prefix: str = "") -> str | None:
    try:
        sig = inspect.signature(value)
    except (TypeError, ValueError):
        return None
    return f"`{prefix}{sig}`" if prefix else f"`{sig}`"


def _iter_public_names(module: ModuleType) -> list[str]:
    explicit = getattr(module, "__all__", None)
    if explicit is not None:
        return [str(name) for name in explicit]
    return [name for name in sorted(dir(module)) if not name.startswith("_")]


def _iter_class_members(cls: type[Any]) -> list[tuple[str, Any]]:
    members: list[tuple[str, Any]] = []
    for name, raw_member in cls.__dict__.items():
        if name.startswith("_"):
            continue

        member = raw_member
        if isinstance(raw_member, (staticmethod, classmethod)):
            member = raw_member.__func__

        if inspect.isfunction(member) or inspect.isbuiltin(member) or isinstance(raw_member, property):
            members.append((name, raw_member))

    return members


def _render_class(name: str, cls: type[Any]) -> list[str]:
    lines = [f"## `{name}`", ""]
    signature = _format_signature(cls, prefix=f"class {name}")
    if signature:
        lines.extend([signature, ""])

    lines.extend([_format_docstring(cls), ""])

    members = _iter_class_members(cls)
    if members:
        lines.extend(["### Members", ""])

    for member_name, raw_member in members:
        if isinstance(raw_member, property):
            lines.extend([f"#### `{member_name}`", "", "`property`", "", _format_docstring(raw_member), ""])
            continue

        target = raw_member
        if isinstance(raw_member, (staticmethod, classmethod)):
            target = raw_member.__func__

        kind = "method"
        if isinstance(raw_member, staticmethod):
            kind = "staticmethod"
        elif isinstance(raw_member, classmethod):
            kind = "classmethod"

        signature = _format_signature(target, prefix=f"{member_name}")
        lines.append(f"#### `{member_name}`")
        lines.append("")
        if signature:
            lines.append(signature)
            lines.append("")
        lines.append(f"`{kind}`")
        lines.append("")
        lines.append(_format_docstring(target))
        lines.append("")

    return lines


def _render_function(name: str, fn: Any) -> list[str]:
    lines = [f"## `{name}`", ""]
    signature = _format_signature(fn, prefix=name)
    if signature:
        lines.extend([signature, ""])
    lines.extend([_format_docstring(fn), ""])
    return lines


def _render_value(name: str, value: Any) -> list[str]:
    lines = [f"## `{name}`", "", "`value`", "", _format_docstring(value), ""]
    return lines


def _render_module_page(module_name: str) -> str:
    try:
        module = importlib.import_module(module_name)
    except ModuleNotFoundError as exc:
        raise RuntimeError(
            f"Could not import '{module_name}'. Install the package into the active environment "
            "first (for example: `pip install -e .`)."
        ) from exc
    title = module_name.split(".")[-1].replace("_", " ").title()

    lines: list[str] = [
        f"# {title} API",
        "",
        "_This file is auto-generated by `tools/generate_api_docs.py`. Do not edit manually._",
        "",
        f"## Module `{module_name}`",
        "",
        _format_docstring(module),
        "",
    ]

    for name in _iter_public_names(module):
        if not hasattr(module, name):
            continue
        value = getattr(module, name)

        if inspect.isclass(value):
            lines.extend(_render_class(name, value))
        elif inspect.isfunction(value) or inspect.isbuiltin(value):
            lines.extend(_render_function(name, value))
        else:
            lines.extend(_render_value(name, value))

    return "\n".join(lines).rstrip() + "\n"


def _parse_module_args(values: list[str] | None) -> dict[str, str]:
    if not values:
        return DEFAULT_MODULE_MAP

    parsed: dict[str, str] = {}
    for item in values:
        if "=" not in item:
            raise ValueError(f"Invalid --module '{item}'. Expected '<slug>=<module.path>'.")
        slug, module_name = item.split("=", maxsplit=1)
        slug = slug.strip()
        module_name = module_name.strip()
        if not slug or not module_name:
            raise ValueError(f"Invalid --module '{item}'. Expected '<slug>=<module.path>'.")
        parsed[slug] = module_name

    return parsed


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("docs/api"),
        help="Output directory for generated Markdown API pages.",
    )
    parser.add_argument(
        "--module",
        action="append",
        default=None,
        help="Module mapping in '<slug>=<module.path>' form. Can be passed multiple times.",
    )
    args = parser.parse_args()

    module_map = _parse_module_args(args.module)

    out_dir: Path = args.out_dir
    out_dir.mkdir(parents=True, exist_ok=True)

    for slug, module_name in module_map.items():
        output_path = out_dir / f"{slug}.md"
        output_path.write_text(_render_module_page(module_name), encoding="utf-8")
        print(f"Wrote {output_path}")


if __name__ == "__main__":
    main()
